backend:
  name: git-gateway
  branch: master
media_folder: static/img/uploads
public_folder: /img/uploads
collections:
  - name: hjem
    label: Hjem
    folder: src/content
    filter:
      field: pageName
      value: Hjem
    create: false
    fields:
      - label: Overskrift
        name: header
        widget: string
      - label: Promo tekst
        name: promoText
        widget: string
      - label: Tjenester
        name: ourServices
        widget: list
        fields:
          - label: Titel
            name: header
            widget: string
          - label: Tekst
            name: description
            widget: text
          - label: Ikon
            name: icon
            widget: string
      - label: Team title
        name: teamHeader
        widget: string
      - label: Team
        name: team
        widget: list
        fields:
          - label: Navn
            name: name
            widget: string
          - label: Tekst
            name: description
            widget: text
          - label: Linkedin
            name: linkedinUrl
            widget: string
            required: false
          - label: GitHub
            name: githubUrl
            widget: string
            required: false
  - name: nettsider
    label: Nettsider
    folder: src/content
    filter:
      field: pageName
      value: Nettsider
    create: false
    fields:
      - label: Overskrift
        name: header
        widget: string
      - label: Tekst
        name: body
        widget: markdown
      - label: Sjekkliste overskrift
        name: checklistHeader
        widget: string
      - label: Sjekkliste
        name: checklist
        widget: list
      - label: Portfolio overskrift
        name: portfolioHeader
        widget: string
      - label: Portfolio
        name: portfolio
        widget: list
        fields:
          - label: Titel
            name: title
            widget: string
          - label: Tekst
            name: description
            widget: text
          - label: Nettaddresse
            name: url
            widget: string
  - name: apper
    label: Apper
    folder: src/content
    filter:
      field: pageName
      value: Apper
    create: false
    fields:
      - label: Overskrift
        name: header
        widget: string
      - label: Tekst
        name: body
        widget: markdown
      - label: Sjekkliste overskrift
        name: checklistHeader
        widget: string
      - label: Sjekkliste
        name: checklist
        widget: list
      - label: Tjenester
        name: ourServices
        widget: list
        fields:
          - label: Titel
            name: header
            widget: string
          - label: Tekst
            name: description
            widget: text
          - label: Ikon
            name: icon
            widget: string
  - name: Systemutvikling
    label: Systemutvikling
    folder: src/content
    filter:
      field: pageName
      value: Systemutvikling
    create: false
    fields:
      - label: Overskrift
        name: header
        widget: string
      - label: Tekst
        name: body
        widget: markdown
      - label: Sjekkliste overskrift
        name: checklistHeader
        widget: string
      - label: Sjekkliste
        name: checklist
        widget: list
      - label: Teknologier overskrift
        name: technologiesHeader
        widget: string
      - label: Teknologier
        name: technologies
        widget: list 